### PR TITLE
Prepping for GF release

### PR DESCRIPTION
**Pull request by aaronbell**
Hi all, 

I've gone through and prepped the fonts for release with GF. For both the Hentaigana set, as well as the 'standard' set, I've gone through and split out the shared glyphs from the unique glyphs, then remerged them during the build process. This allows us to maintain a single source file for each glyph. 

Additional changes:
- Added full GF Core Latin coverage where missing
- Added BASE table
- Updated metadata

Please take a look at the fonts and ensure that they meet your expectations.

```
                           ,@.
                         ,@.@@,.
                   ,@@,.@@@.  @.@@@,.
                 ,@@. @@@.     @@. @@,.
         ,@@@.@,.@.              @.  @@@@,.@.@@,.
    ,@@.@.     @@.@@.            @,.    .@’ @’  @@,
  ,@@. @.          .@@.@@@.  @@’                  @,
 ,@.  @@.                                          @,
 @.     @,@@,.     ,                             .@@,
 @,.       .@,@@,.         .@@,.  ,       .@@,  @, @,
 @.                             .@. @ @@,.    ,      @
  @,.@@.     @,.      @@,.      @.           @,.    @’
   @@||@,.  @’@,.       @@,.  @@ @,.        @’@@,  @’
      \\@@@@’  @,.      @’@@@@’   @@,.   @@@’ //@@@’
       |||||||| @@,.  @@’ |||||||  |@@@|@||  ||
        \\\\\\\  ||@@@||  |||||||  |||||||  //
         |||||||  ||||||  ||||||   ||||||  ||
          \\\\\\  ||||||  ||||||  ||||||  //
           ||||||  |||||  |||||   |||||  ||
            \\\\\  |||||  |||||  |||||  //
             |||||  ||||  |||||  ||||  ||
              \\\\  ||||  ||||  ||||  //
               ||||||||||||||||||||||||

         No check is failing. Get a cupcake!
       <<Art by Tony de Marco, July 26, 2018>>
```

### CODE REVIEW

**Comment by aaronbell** [comment]
Last thing missing is a description for each font. If you can provide that, then we'll be ready!

**Comment by kiryumi** [comment]
Sorry, I accidentally merged it. Please check.

**Comment by aaronbell** [comment]
No problem. Did you have a chance to check the font files to ensure that they are working as desired?

**Comment by kiryumi** [comment]
Yes, I have checked the TTF. Thank you very much! But I couldn't find the OTF.

**Comment by aaronbell** [comment]
@kiryumi GF only requires a TTF file. Would you also an OTF to be generated?

**Comment by kiryumi** [comment]
@aaronbell I understand. I'll upload the OTF file. Thank you.

**Comment by aaronbell** [comment]
@kiryumi Oh, no need. Better that I generate to keep consistent. I'll add it to my build script. 

Meanwhile, can you provide a description for each of the 5 font families that I can use when uploading the fonts to GF?

**Comment by kiryumi** [comment]
@aaronbell We have no problem with TTF only. Sorry for the confusion.

I noticed that the description of the 5 typefaces is only in Japanese. I will add text.

**Pull request merged**
